plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.guava:guava:31.1-jre'
    implementation 'com.fasterxml.jackson.core:jackson-annotations:2.15.3'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.15.3'
    testImplementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.15.3'
    testImplementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.3'
}
